export interface DestinationImageSeed {
  imageUrl: string;
  isPrimary: boolean;
  displayOrder: number;
}

export interface DestinationSeedItem {
  name: string;
  aliases?: string[];
  description: string;
  address: string;
  phoneNumber?: string | null;
  latitude: string;
  longitude: string;
  ticketPrice: number;
  openingHoursNote: string;
  visitDuration: number;
  categoryNames: string[];
  images: DestinationImageSeed[];
}

export const DESTINATIONS_DATA: DestinationSeedItem[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // MIỀN BẮC (10 ĐỊA ĐIỂM)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Vịnh Hạ Long',
    description: 'Di sản thiên nhiên thế giới được UNESCO công nhận với hàng ngàn đảo đá vôi kỳ vĩ nhô lên từ làn nước xanh ngọc bích, tạo nên tuyệt tác thiên nhiên độc nhất vô nhị.',
    address: 'Thành phố Hạ Long, tỉnh Quảng Ninh',
    latitude: '20.9100500',
    longitude: '107.1839000',
    ticketPrice: 290_000,
    openingHoursNote: 'Tàu tham quan khởi hành từ 06:30 đến 16:30 hàng ngày tại Cảng tàu khách quốc tế Hạ Long.',
    visitDuration: 240,
    categoryNames: ['Biển đảo', 'Thiên nhiên', 'Nghỉ dưỡng'],
    images: [
      { imageUrl: '/images/destinations/ha-long.webp', isPrimary: true, displayOrder: 0 },
      { imageUrl: '/images/vietnam-ai-planner.jpg', isPrimary: false, displayOrder: 1 },
    ],
  },
  {
    name: 'Quần thể danh thắng Tràng An',
    description: 'Di sản Văn hóa và Thiên nhiên thế giới hỗn hợp đầu tiên tại Đông Nam Á, nổi bật với hệ thống hang động xuyên thủy, đền chùa thanh tịnh và thung lũng đá vôi ngập nước.',
    address: 'Xã Ninh Xuân, huyện Hoa Lư, tỉnh Ninh Bình',
    latitude: '20.2536000',
    longitude: '105.9126000',
    ticketPrice: 250_000,
    openingHoursNote: 'Mở cửa tham quan bằng thuyền chèo tay từ 07:00 đến 17:00 hàng ngày.',
    visitDuration: 180,
    categoryNames: ['Thiên nhiên', 'Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/trang-an.webp', isPrimary: true, displayOrder: 0 },
      { imageUrl: '/images/vietnam-ninh-binh-discovery.jpg', isPrimary: false, displayOrder: 1 },
    ],
  },
  {
    name: 'Tam Cốc – Bích Động',
    description: 'Được mệnh danh là Nam thiên đệ nhị động, Tam Cốc quyến rũ với dòng sông Ngô Đồng uốn lượn qua những ruộng lúa chín vàng óng và ba hang động tự nhiên huyền ảo.',
    address: 'Xã Ninh Hải, huyện Hoa Lư, tỉnh Ninh Bình',
    latitude: '20.2185000',
    longitude: '105.9392000',
    ticketPrice: 120_000,
    openingHoursNote: 'Thời gian tham quan đẹp nhất vào mùa lúa chín tháng 5 - tháng 6, mở cửa từ 07:30 đến 17:30.',
    visitDuration: 120,
    categoryNames: ['Thiên nhiên', 'Văn hóa'],
    images: [
      { imageUrl: '/images/vietnam-ninh-binh-discovery.jpg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Phố cổ Hà Nội',
    description: 'Không gian văn hóa đặc sắc với 36 phố phường lưu giữ kiến trúc đầu thế kỷ XX, các làng nghề truyền thống và thiên đường ẩm thực đường phố sôi động.',
    address: 'Phường Hàng Bạc, quận Hoàn Kiếm, thành phố Hà Nội',
    latitude: '21.0341000',
    longitude: '105.8507000',
    ticketPrice: 0,
    openingHoursNote: 'Khu phố mở cửa cả ngày; phố đi bộ cuối tuần hoạt động từ tối thứ Sáu đến hết Chủ nhật.',
    visitDuration: 150,
    categoryNames: ['Văn hóa', 'Ẩm thực', 'Thành phố'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Văn Miếu – Quốc Tử Giám',
    aliases: ['Văn Miếu - Quốc Tử Giám'],
    description: 'Trường đại học đầu tiên của Việt Nam, biểu tượng tinh hoa hiếu học của dân tộc với 82 tấm bia tiến sĩ bằng đá ngự trên lưng rùa được UNESCO công nhận là di sản tư liệu.',
    address: '58 Quốc Tử Giám, quận Đống Đa, thành phố Hà Nội',
    latitude: '21.0280430',
    longitude: '105.8354820',
    ticketPrice: 70_000,
    openingHoursNote: 'Mở cửa từ 08:00 đến 17:00 hàng ngày; các dịp lễ tết có chương trình trải nghiệm ánh sáng ban đêm.',
    visitDuration: 90,
    categoryNames: ['Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Hồ Hoàn Kiếm',
    description: 'Trái tim của Thủ đô Hà Nội gắn liền với truyền thuyết vua Lê Lợi trả gươm thần, nơi có Tháp Rùa cổ kính, cầu Thê Húc son đỏ dẫn vào Đền Ngọc Sơn uy nghiêm.',
    address: 'Phường Hàng Trống, quận Hoàn Kiếm, thành phố Hà Nội',
    latitude: '21.0286669',
    longitude: '105.8521484',
    ticketPrice: 0,
    openingHoursNote: 'Khuôn viên hồ mở cửa 24/7; Đền Ngọc Sơn mở cửa bán vé từ 07:00 đến 18:00.',
    visitDuration: 90,
    categoryNames: ['Lịch sử', 'Văn hóa', 'Thành phố'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Thị trấn Sa Pa',
    description: 'Thị trấn mờ sương nép mình dưới dãy Hoàng Liên Sơn hùng vĩ, nổi tiếng với khí hậu ôn đới mát lạnh, ruộng bậc thang tầng tầng lớp lớp và bản sắc văn hóa các dân tộc Mông, Dao.',
    address: 'Thị xã Sa Pa, tỉnh Lào Cai',
    latitude: '22.3364000',
    longitude: '103.8438000',
    ticketPrice: 0,
    openingHoursNote: 'Thời điểm tham quan lý tưởng từ tháng 9 đến tháng 11 hoặc mùa hoa nở tháng 2 - tháng 4.',
    visitDuration: 180,
    categoryNames: ['Thiên nhiên', 'Nghỉ dưỡng', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/sa-pa.webp', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Đỉnh Fansipan',
    description: 'Nóc nhà Đông Dương với độ cao 3.143m so với mực nước biển, điểm đến săn mây ngoạn mục trên đỉnh trời cùng quần thể công trình tâm linh kỳ vĩ trên vách đá.',
    address: 'Dãy Hoàng Liên Sơn, thị xã Sa Pa, tỉnh Lào Cai',
    latitude: '22.3034000',
    longitude: '103.7752000',
    ticketPrice: 850_000,
    openingHoursNote: 'Cáp treo Sun World Fansipan Legend hoạt động từ 08:00 đến 17:30 các ngày trong tuần.',
    visitDuration: 240,
    categoryNames: ['Phiêu lưu', 'Thiên nhiên'],
    images: [
      { imageUrl: '/images/destinations/sa-pa.webp', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Cao nguyên đá Đồng Văn',
    description: 'Công viên địa chất toàn cầu UNESCO sở hữu cảnh quan núi đá tai mèo hùng vĩ, hẻm vực Tu Sản sâu nhất Đông Nam Á cùng cung đường đèo Mã Pí Lèng trứ danh.',
    address: 'Huyện Đồng Văn, tỉnh Hà Giang',
    latitude: '23.2789000',
    longitude: '105.3621000',
    ticketPrice: 0,
    openingHoursNote: 'Tham quan tự do quanh năm; mùa hoa tam giác mạch rực rỡ nhất vào tháng 10 - tháng 11.',
    visitDuration: 240,
    categoryNames: ['Thiên nhiên', 'Phiêu lưu', 'Văn hóa'],
    images: [
      { imageUrl: '/images/vietnam-ha-giang-hero.jpg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Thác Bản Giốc',
    description: 'Một trong những thác nước tự nhiên đẹp nhất thế giới nằm trên đường biên giới Việt - Trung, dòng nước trắng xóa đổ xuống ba tầng giữa thung lũng đá vôi tươi tốt.',
    address: 'Xã Đàm Thủy, huyện Trùng Khánh, tỉnh Cao Bằng',
    latitude: '22.8542000',
    longitude: '106.7239000',
    ticketPrice: 45_000,
    openingHoursNote: 'Mở cửa từ 07:00 đến 17:30; nên đi thuyền bè ngắm chân thác để cảm nhận trọn vẹn sự kỳ vĩ.',
    visitDuration: 150,
    categoryNames: ['Thiên nhiên', 'Phiêu lưu'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // MIỀN TRUNG (10 ĐỊA ĐIỂM)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Phố cổ Hội An',
    description: 'Đô thị cổ được bảo tồn gần như nguyên vẹn với những dãy nhà tường vàng mái ngói phủ rêu phong, đèn lồng rực rỡ và dòng sông Hoài êm đềm mang đậm dấu ấn thương cảng quốc tế thế kỷ XVII.',
    address: 'Phường Minh An, thành phố Hội An, tỉnh Quảng Nam',
    latitude: '15.8801000',
    longitude: '108.3380000',
    ticketPrice: 80_000,
    openingHoursNote: 'Khu phố đi bộ hoạt động từ 09:00 đến 11:00 và từ 15:00 đến 21:30 hàng ngày.',
    visitDuration: 180,
    categoryNames: ['Văn hóa', 'Lịch sử', 'Ẩm thực'],
    images: [
      { imageUrl: '/images/destinations/hoi-an.webp', isPrimary: true, displayOrder: 0 },
      { imageUrl: '/images/vietnam-hoi-an-journal.jpg', isPrimary: false, displayOrder: 1 },
    ],
  },
  {
    name: 'Thánh địa Mỹ Sơn',
    description: 'Quần thể đền tháp Chăm Pa cổ nằm ẩn mình trong thung lũng bao quanh bởi đồi núi trùng điệp, mang kiến trúc gạch nung tinh xảo thờ thần Shiva từ thế kỷ IV đến thế kỷ XIV.',
    address: 'Xã Duy Phú, huyện Duy Xuyên, tỉnh Quảng Nam',
    latitude: '15.7958000',
    longitude: '108.1244000',
    ticketPrice: 150_000,
    openingHoursNote: 'Mở cửa từ 06:30 đến 17:00; có các suất biểu diễn múa Chăm miễn phí hàng ngày.',
    visitDuration: 150,
    categoryNames: ['Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Đại Nội Huế',
    description: 'Hoàng thành và Tử Cấm Thành của triều đại phong kiến cuối cùng tại Việt Nam, hội tụ các cung điện nguy nga, vườn thượng uyển và đền đài uy nghiêm bên dòng sông Hương.',
    address: 'Đường 23/8, phường Thuận Hòa, thành phố Huế, tỉnh Thừa Thiên Huế',
    latitude: '16.4697000',
    longitude: '107.5779000',
    ticketPrice: 200_000,
    openingHoursNote: 'Mở cửa tham quan từ 07:30 đến 17:30 hàng ngày.',
    visitDuration: 180,
    categoryNames: ['Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Cố đô Huế',
    description: 'Quần thể di tích Cố đô Huế bao gồm lăng tẩm các vị vua triều Nguyễn, chùa Thiên Mụ cổ kính và dòng sông Hương thơ mộng gắn liền với nghệ thuật ca Huế.',
    address: 'Thành phố Huế, tỉnh Thừa Thiên Huế',
    latitude: '16.4637000',
    longitude: '107.5909000',
    ticketPrice: 0,
    openingHoursNote: 'Các điểm lăng tẩm và chùa chiền mở cửa ban ngày theo quy định riêng của Trung tâm BTTN Cố đô.',
    visitDuration: 180,
    categoryNames: ['Lịch sử', 'Văn hóa', 'Ẩm thực'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Động Phong Nha',
    description: 'Kỳ quan đệ nhất động nổi tiếng với 7 cái nhất thế giới: sông ngầm dài nhất, cửa hang cao và rộng nhất, bãi cát và bãi đá ngầm đẹp nhất cùng thạch nhũ huyền ảo.',
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Bình',
    latitude: '17.5898000',
    longitude: '106.2829000',
    ticketPrice: 150_000,
    openingHoursNote: 'Mở cửa từ 07:30 đến 16:30; di chuyển bằng thuyền máy từ trung tâm du lịch Phong Nha.',
    visitDuration: 180,
    categoryNames: ['Thiên nhiên', 'Phiêu lưu'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Hang Sơn Đoòng',
    description: 'Hang động tự nhiên lớn nhất thế giới với hệ sinh thái rừng nhiệt đới riêng biệt bên trong lòng đất, có mây mù bao phủ và khối măng đá cao sừng sững.',
    address: 'Vườn quốc gia Phong Nha - Kẻ Bàng, tỉnh Quảng Bình',
    latitude: '17.4568000',
    longitude: '106.2874000',
    ticketPrice: 72_000_000,
    openingHoursNote: 'Chỉ đón khách qua các tour thám hiểm chuyên nghiệp giới hạn số lượng theo mùa từ tháng 1 đến tháng 8.',
    visitDuration: 240,
    categoryNames: ['Phiêu lưu', 'Thiên nhiên'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Bà Nà Hills',
    description: 'Khu du lịch trên đỉnh núi Chúa ở độ cao 1.487m với khí hậu bốn mùa trong một ngày, nổi tiếng toàn cầu với công trình kiến trúc Cầu Vàng sừng sững giữa biển mây.',
    address: 'Xã Hòa Ninh, huyện Hòa Vang, thành phố Đà Nẵng',
    latitude: '15.9953000',
    longitude: '107.9967000',
    ticketPrice: 900_000,
    openingHoursNote: 'Hệ thống cáp treo vận hành từ 08:00 đến 17:00 các ngày trong tuần.',
    visitDuration: 240,
    categoryNames: ['Nghỉ dưỡng', 'Thành phố', 'Thiên nhiên'],
    images: [
      { imageUrl: '/images/destinations/da-nang.webp', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Bán đảo Sơn Trà',
    description: 'Lá phổi xanh của thành phố biển Đà Nẵng, nơi bảo tồn loài voọc chà vá chân nâu quý hiếm cùng các cung đường ven biển ngoạn mục dẫn lên đỉnh Bàn Cờ.',
    address: 'Quận Sơn Trà, thành phố Đà Nẵng',
    latitude: '16.1153000',
    longitude: '108.2750000',
    ticketPrice: 0,
    openingHoursNote: 'Tham quan tự do ban ngày; nên tránh lên núi vào các ngày sương mù hoặc mưa dông.',
    visitDuration: 150,
    categoryNames: ['Thiên nhiên', 'Biển đảo'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Bãi biển Mỹ Khê',
    description: 'Một trong những bãi biển quyến rũ nhất hành tinh được tạp chí Forbes bình chọn, với bờ cát mịn thoai thoải, làn nước trong xanh và hàng dừa đung đưa trong gió biển.',
    address: 'Đường Võ Nguyên Giáp, quận Sơn Trà, thành phố Đà Nẵng',
    latitude: '16.0544068',
    longitude: '108.2472344',
    ticketPrice: 0,
    openingHoursNote: 'Tắm biển an toàn trong khung giờ có lực lượng cứu hộ túc trực từ 05:00 đến 18:30.',
    visitDuration: 120,
    categoryNames: ['Biển đảo', 'Nghỉ dưỡng'],
    images: [
      { imageUrl: '/images/destinations/da-nang.webp', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Eo Gió Quy Nhơn',
    description: 'Thắng cảnh biển kỳ vĩ với rặng đá uốn lượn ôm trọn bờ biển xanh biếc, con đường đi bộ ven vách núi mang vẻ đẹp hoang sơ tựa như Jeju của Việt Nam.',
    address: 'Xã Nhơn Lý, thành phố Quy Nhơn, tỉnh Bình Định',
    latitude: '13.9213000',
    longitude: '109.2882000',
    ticketPrice: 25_000,
    openingHoursNote: 'Thời điểm ngắm bình minh và hoàng hôn đẹp nhất, mở cửa từ 06:00 đến 18:00.',
    visitDuration: 120,
    categoryNames: ['Biển đảo', 'Thiên nhiên'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // MIỀN NAM VÀ TÂY NGUYÊN (10 ĐỊA ĐIỂM)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Chợ Bến Thành',
    description: 'Biểu tượng lịch sử và thương mại phồn hoa của Sài Gòn hơn một thế kỷ qua với tháp đồng hồ bốn mặt nổi bật, nơi hội tụ hàng ngàn món ăn đặc sản và quà lưu niệm tinh tế.',
    address: 'Đường Lê Lợi, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh',
    latitude: '10.7725260',
    longitude: '106.6980410',
    ticketPrice: 0,
    openingHoursNote: 'Chợ truyền thống hoạt động từ 06:00 đến 18:00; chợ đêm xung quanh mở cửa đến khuya.',
    visitDuration: 90,
    categoryNames: ['Ẩm thực', 'Thành phố', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Dinh Độc Lập',
    description: 'Di tích lịch sử quốc gia đặc biệt ghi dấu mốc son thống nhất đất nước ngày 30/4/1975, công trình kiến trúc kết hợp hài hòa giữa hiện đại phương Tây và triết lý phương Đông.',
    address: '135 Nam Kỳ Khởi Nghĩa, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh',
    latitude: '10.7770280',
    longitude: '106.6953020',
    ticketPrice: 65_000,
    openingHoursNote: 'Mở cửa tham quan từ 08:00 đến 16:30 tất cả các ngày trong tuần.',
    visitDuration: 120,
    categoryNames: ['Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Địa đạo Củ Chi',
    description: 'Kỳ quan nghệ thuật quân sự với hệ thống đường hầm bí mật sâu trong lòng đất dài hơn 250km, biểu tượng kiên cường bất khuất trong cuộc kháng chiến chống giặc ngoại xâm.',
    address: 'Tỉnh lộ 15, xã Phú Mỹ Hưng, huyện Củ Chi, TP. Hồ Chí Minh',
    latitude: '11.1444000',
    longitude: '106.4633000',
    ticketPrice: 125_000,
    openingHoursNote: 'Mở cửa từ 07:00 đến 17:00 hàng ngày; có khu bắn súng thể thao quốc phòng.',
    visitDuration: 180,
    categoryNames: ['Lịch sử', 'Phiêu lưu'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Thành phố Đà Lạt',
    description: 'Thành phố ngàn hoa trên cao nguyên Lâm Viên với khí hậu mát lành quanh năm, những đồi thông reo trong sương sớm, các biệt thự Pháp cổ kính và vườn dâu tây sum suê.',
    address: 'Thành phố Đà Lạt, tỉnh Lâm Đồng',
    latitude: '11.9404000',
    longitude: '108.4583000',
    ticketPrice: 0,
    openingHoursNote: 'Thời tiết mát mẻ quanh năm, đẹp nhất từ tháng 11 đến tháng 4 mùa hoa dã quỳ và mai anh đào.',
    visitDuration: 180,
    categoryNames: ['Nghỉ dưỡng', 'Thiên nhiên', 'Ẩm thực'],
    images: [
      { imageUrl: '/images/destinations/da-lat.webp', isPrimary: true, displayOrder: 0 },
      { imageUrl: '/images/vietnam-dalat-roadtrip.jpg', isPrimary: false, displayOrder: 1 },
    ],
  },
  {
    name: 'Hồ Xuân Hương',
    description: 'Viên ngọc bích giữa trung tâm thành phố Đà Lạt, nơi lý tưởng để đạp vịt, đi dạo quanh hồ dưới bóng thông reo và thưởng thức cà phê ngắm hoàng hôn lãng mạn.',
    address: 'Phường 1, thành phố Đà Lạt, tỉnh Lâm Đồng',
    latitude: '11.9427000',
    longitude: '108.4452000',
    ticketPrice: 0,
    openingHoursNote: 'Khu vực mở cửa tự do 24/7; có dịch vụ thuê xe đạp đôi và xe ngựa dạo quanh hồ.',
    visitDuration: 90,
    categoryNames: ['Thiên nhiên', 'Nghỉ dưỡng'],
    images: [
      { imageUrl: '/images/destinations/da-lat.webp', isPrimary: true, displayOrder: 0 },
      { imageUrl: '/images/vietnam-dalat-roadtrip.jpg', isPrimary: false, displayOrder: 1 },
    ],
  },
  {
    name: 'Đồi cát Mũi Né',
    description: 'Sa mạc cát đỏ và cát trắng thay đổi hình dạng theo từng cơn gió biển, thiên đường trải nghiệm trượt cát mạo hiểm và lái xe địa hình ngắm bình minh trên đồi cát.',
    address: 'Khu phố 5, phường Mũi Né, thành phố Phan Thiết, tỉnh Bình Thuận',
    latitude: '10.9422000',
    longitude: '108.2917000',
    ticketPrice: 0,
    openingHoursNote: 'Nên tham quan từ 05:00 đến 08:00 sáng hoặc sau 16:00 chiều để tránh nắng gắt.',
    visitDuration: 120,
    categoryNames: ['Thiên nhiên', 'Phiêu lưu'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Chợ nổi Cái Răng',
    description: 'Chợ nổi bán buôn lớn nhất vùng đồng bằng sông Cửu Long, nơi hàng trăm ghe thuyền tấp nập trao đổi hoa quả nông sản với cây bẹo treo hàng hóa đặc trưng sông nước Nam Bộ.',
    address: '46 Hai Bà Trưng, quận Cái Răng, thành phố Cần Thơ',
    latitude: '10.0039000',
    longitude: '105.7483000',
    ticketPrice: 0,
    openingHoursNote: 'Chợ họp nhộn nhịp nhất từ 05:00 đến 08:00 sáng; nên thuê thuyền xuất phát từ bến Ninh Kiều sớm.',
    visitDuration: 150,
    categoryNames: ['Văn hóa', 'Ẩm thực'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Đảo Phú Quốc',
    description: 'Đảo Ngọc phía Tây Nam Tổ quốc với những bãi tắm hoang sơ bờ cát trắng mịn màng như Bãi Sao, Bãi Khem, các khu bảo tồn san hô rực rỡ và làng chài Hàm Ninh trù phú.',
    address: 'Thành phố Phú Quốc, tỉnh Kiên Giang',
    latitude: '10.2289000',
    longitude: '103.9572000',
    ticketPrice: 0,
    openingHoursNote: 'Mùa khô đẹp nhất từ tháng 11 đến tháng 4 hàng năm với biển êm nắng ấm.',
    visitDuration: 240,
    categoryNames: ['Biển đảo', 'Nghỉ dưỡng'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Côn Đảo',
    description: 'Quần đảo thiêng liêng giữa đại dương xanh thẳm, nơi ghi dấu lịch sử anh hùng bất khuất tại Nhà tù Côn Đảo và sở hữu hệ sinh thái biển đảo nguyên sinh với rùa biển đẻ trứng.',
    address: 'Huyện Côn Đảo, tỉnh Bà Rịa - Vũng Tàu',
    latitude: '8.6835000',
    longitude: '106.6087000',
    ticketPrice: 0,
    openingHoursNote: 'Di tích nhà tù mở cửa ban ngày; nghĩa trang Hàng Dương mở cửa viếng mộ đến khuya.',
    visitDuration: 240,
    categoryNames: ['Lịch sử', 'Biển đảo', 'Thiên nhiên'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Núi Bà Đen',
    description: 'Nóc nhà Đông Nam Bộ ở độ cao 986m, trung tâm hành hương tâm linh nổi tiếng với tượng Phật Bà bằng đồng cao nhất châu Á và cảnh sắc biển mây kỳ ảo quanh năm.',
    address: 'Xã Thạnh Tân, thành phố Tây Ninh, tỉnh Tây Ninh',
    latitude: '11.3748000',
    longitude: '106.1689000',
    ticketPrice: 250_000,
    openingHoursNote: 'Cáp treo Sun World Ba Den Mountain hoạt động từ 06:00 đến 21:00 hàng ngày.',
    visitDuration: 180,
    categoryNames: ['Văn hóa', 'Thiên nhiên', 'Phiêu lưu'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BỔ SUNG ĐỒNG BỘ 10 ĐỊA ĐIỂM ĐÃ CÓ TRONG HỆ THỐNG
  // ─────────────────────────────────────────────────────────────────────────────
  {
    name: 'Hoàng thành Thăng Long',
    description: 'Di sản văn hóa thế giới với các lớp di tích khảo cổ và kiến trúc gắn với lịch sử kinh thành Thăng Long nghìn năm văn hiến.',
    address: '19C Hoàng Diệu, phường Ba Đình, Hà Nội',
    latitude: '21.0352410',
    longitude: '105.8402890',
    ticketPrice: 70_000,
    openingHoursNote: 'Mở cửa ban ngày từ 08:00 đến 17:00, thường đóng cửa thứ Hai; kiểm tra lịch vận hành trước chuyến đi.',
    visitDuration: 120,
    categoryNames: ['Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Bảo tàng Dân tộc học Việt Nam',
    description: 'Bảo tàng trưng bày văn hóa, kiến trúc và đời sống của 54 dân tộc Việt Nam với khu ngoài trời mô phỏng nhà rông, nhà dài đặc sắc.',
    address: '1 Nguyễn Văn Huyên, phường Nghĩa Đô, quận Cầu Giấy, Hà Nội',
    latitude: '21.0403490',
    longitude: '105.7980900',
    ticketPrice: 40_000,
    openingHoursNote: 'Mở cửa từ 08:30 đến 17:30 các ngày từ thứ Ba đến Chủ nhật (đóng cửa thứ Hai).',
    visitDuration: 150,
    categoryNames: ['Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Phố ẩm thực Tạ Hiện',
    description: 'Tuyến phố sôi động trong khu phố cổ, tập trung món ăn đường phố đặc sắc và hoạt động giải trí về đêm của giới trẻ và du khách quốc tế.',
    address: 'Phố Tạ Hiện, phường Hàng Buồm, quận Hoàn Kiếm, Hà Nội',
    latitude: '21.0352420',
    longitude: '105.8521620',
    ticketPrice: 0,
    openingHoursNote: 'Các hàng quán hoạt động chủ yếu từ chiều tối đến khuya, nhộn nhịp nhất sau 19:00.',
    visitDuration: 120,
    categoryNames: ['Ẩm thực', 'Thành phố'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Danh thắng Ngũ Hành Sơn',
    description: 'Quần thể sáu ngọn núi đá vôi mang tên ngũ hành, ẩn chứa nhiều hang động huyền bí và chùa cổ linh thiêng bên bờ biển Đà Nẵng.',
    address: '81 Huyền Trân Công Chúa, phường Hòa Hải, quận Ngũ Hành Sơn, Đà Nẵng',
    latitude: '16.0034180',
    longitude: '108.2631290',
    ticketPrice: 40_000,
    openingHoursNote: 'Mở cửa từ 07:00 đến 17:30 hàng ngày; có hệ thống thang máy phục vụ lên núi.',
    visitDuration: 150,
    categoryNames: ['Thiên nhiên', 'Lịch sử'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Chùa Linh Ứng Sơn Trà',
    description: 'Ngôi chùa trên bán đảo Sơn Trà nổi bật với tượng Phật Bà Quan Thế Âm cao 67m hướng ra biển và tầm nhìn bao quát toàn cảnh vịnh Đà Nẵng.',
    address: 'Bãi Bụt, bán đảo Sơn Trà, quận Sơn Trà, Đà Nẵng',
    latitude: '16.1002910',
    longitude: '108.2770780',
    ticketPrice: 0,
    openingHoursNote: 'Mở cửa từ 06:00 đến 21:00; du khách chú ý trang phục lịch sự tại nơi thờ tự.',
    visitDuration: 90,
    categoryNames: ['Thiên nhiên', 'Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Cầu Rồng Đà Nẵng',
    description: 'Công trình biểu tượng bắc qua sông Hàn với hình dáng rồng thời Lý vươn ra biển lớn, nổi tiếng với màn trình diễn phun lửa và phun nước cuối tuần.',
    address: 'Đường Nguyễn Văn Linh, phường Phước Ninh, quận Hải Châu, Đà Nẵng',
    latitude: '16.0610750',
    longitude: '108.2274540',
    ticketPrice: 0,
    openingHoursNote: 'Tham quan tự do 24/7; phun lửa và phun nước lúc 21:00 các tối thứ Bảy và Chủ nhật.',
    visitDuration: 60,
    categoryNames: ['Thành phố', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/da-nang.webp', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Chợ Hàn Đà Nẵng',
    description: 'Khu chợ thương mại trung tâm lâu đời, nơi du khách thỏa thích khám phá ẩm thực miền Trung, hải sản khô và các món quà lưu niệm đặc trưng.',
    address: '119 Trần Phú, phường Hải Châu 1, quận Hải Châu, Đà Nẵng',
    latitude: '16.0681870',
    longitude: '108.2231150',
    ticketPrice: 0,
    openingHoursNote: 'Chợ hoạt động từ 06:00 đến 19:00 hàng ngày.',
    visitDuration: 90,
    categoryNames: ['Ẩm thực', 'Thành phố'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Bảo tàng Chứng tích Chiến tranh',
    description: 'Bảo tàng chuyên đề lưu giữ hiện vật, hình ảnh sống động về cuộc chiến tranh bảo vệ Tổ quốc, mang thông điệp hòa bình sâu sắc đến bạn bè quốc tế.',
    address: '28 Võ Văn Tần, Phường Võ Thị Sáu, Quận 3, TP. Hồ Chí Minh',
    latitude: '10.7794760',
    longitude: '106.6921390',
    ticketPrice: 40_000,
    openingHoursNote: 'Mở cửa từ 07:30 đến 17:30 tất cả các ngày trong tuần.',
    visitDuration: 120,
    categoryNames: ['Lịch sử', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Phố đi bộ Nguyễn Huệ',
    description: 'Quảng trường đi bộ trung tâm thành phố kết nối trụ sở UBND TP.HCM và bến Bạch Đằng, nơi diễn ra các lễ hội văn hóa và nhạc nước rực rỡ.',
    address: 'Đường Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    latitude: '10.7744310',
    longitude: '106.7034390',
    ticketPrice: 0,
    openingHoursNote: 'Mở cửa tự do 24/7; cấm phương tiện giao thông vào tối thứ Bảy và Chủ nhật.',
    visitDuration: 90,
    categoryNames: ['Thành phố', 'Ẩm thực'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
  {
    name: 'Bưu điện Trung tâm Sài Gòn',
    description: 'Kiệt tác kiến trúc cổ kính giao thoa phong cách phương Tây và phương Đông do kiến trúc sư người Pháp thiết kế, điểm dừng chân văn hóa không thể bỏ qua.',
    address: '02 Công xã Paris, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    latitude: '10.7797870',
    longitude: '106.6990180',
    ticketPrice: 0,
    openingHoursNote: 'Mở cửa từ 07:30 đến 18:00 các ngày trong tuần, thứ Bảy từ 08:00 đến 18:00, Chủ nhật từ 08:00 đến 17:00.',
    visitDuration: 60,
    categoryNames: ['Lịch sử', 'Thành phố', 'Văn hóa'],
    images: [
      { imageUrl: '/images/destinations/placeholder.svg', isPrimary: true, displayOrder: 0 },
    ],
  },
];
