export interface ItinerarySeedItem {
  destinationName: string;
  sequenceOrder: number;
  startTime: string; // 'HH:mm'
  endTime: string;   // 'HH:mm'
  estimatedCost: number;
  travelDistanceKm: number;
  travelDurationMinutes: number;
  travelMode: 'WALKING' | 'DRIVING' | 'TRANSIT' | 'CYCLING';
  note: string;
}

export interface TripDaySeedItem {
  dayNumber: number;
  note?: string;
  itineraries: ItinerarySeedItem[];
}

export interface TripSeedItem {
  userEmail: string;
  name: string;
  destinationCity: string;
  startDate: string; // 'YYYY-MM-DD'
  endDate: string;   // 'YYYY-MM-DD'
  budget: number;
  numberOfPeople: number;
  description: string;
  isPublic: boolean;
  isAiGenerated: boolean;
  shareToken?: string;
  days: TripDaySeedItem[];
}

export const TRIPS_DATA: TripSeedItem[] = [
  // ─── TRIP 1: Khám phá Hà Nội 3 ngày ──────────────────────────────────────────
  {
    userEmail: 'demo.an@example.com',
    name: 'Khám phá Hà Nội 3 ngày văn hiến',
    destinationCity: 'Hà Nội',
    startDate: '2026-10-10',
    endDate: '2026-10-12',
    budget: 3_500_000,
    numberOfPeople: 2,
    description: 'Hành trình 3 ngày trải nghiệm trọn vẹn văn hóa, lịch sử và nét ẩm thực đặc sắc của thủ đô nghìn năm văn hiến.',
    isPublic: true,
    isAiGenerated: false,
    shareToken: 'demo-share-trip-hanoi-01',
    days: [
      {
        dayNumber: 1,
        note: 'Dạo quanh các con phố cổ kính và tìm hiểu di tích trung tâm thủ đô',
        itineraries: [
          {
            destinationName: 'Phố cổ Hà Nội',
            sequenceOrder: 1,
            startTime: '08:30',
            endTime: '11:30',
            estimatedCost: 100_000,
            travelDistanceKm: 1.2,
            travelDurationMinutes: 15,
            travelMode: 'WALKING',
            note: 'Đi dạo qua các phố Hàng Bạc, Mã Mây, thưởng thức cà phê trứng truyền thống.',
          },
          {
            destinationName: 'Hồ Hoàn Kiếm',
            sequenceOrder: 2,
            startTime: '14:00',
            endTime: '16:30',
            estimatedCost: 30_000,
            travelDistanceKm: 0.8,
            travelDurationMinutes: 10,
            travelMode: 'WALKING',
            note: 'Dạo quanh hồ Gươm, qua cầu Thê Húc màu son vào viếng Đền Ngọc Sơn.',
          },
          {
            destinationName: 'Văn Miếu – Quốc Tử Giám',
            sequenceOrder: 3,
            startTime: '17:30',
            endTime: '19:30',
            estimatedCost: 70_000,
            travelDistanceKm: 3.5,
            travelDurationMinutes: 20,
            travelMode: 'DRIVING',
            note: 'Chiêm ngưỡng bia tiến sĩ và kiến trúc cổ kính Khuê Văn Các buổi chiều tà.',
          },
        ],
      },
      {
        dayNumber: 2,
        note: 'Hành trình khám phá chiều sâu lịch sử và văn hóa giáo dục Thăng Long',
        itineraries: [
          {
            destinationName: 'Văn Miếu – Quốc Tử Giám',
            sequenceOrder: 1,
            startTime: '09:00',
            endTime: '11:30',
            estimatedCost: 70_000,
            travelDistanceKm: 2.0,
            travelDurationMinutes: 15,
            travelMode: 'TRANSIT',
            note: 'Trải nghiệm không gian tĩnh lặng và tìm hiểu đạo học phương Đông.',
          },
          {
            destinationName: 'Phố cổ Hà Nội',
            sequenceOrder: 2,
            startTime: '14:30',
            endTime: '17:30',
            estimatedCost: 150_000,
            travelDistanceKm: 2.8,
            travelDurationMinutes: 20,
            travelMode: 'WALKING',
            note: 'Thưởng thức bún chả, nộm bò khô và ghé thăm nhà cổ Mã Mây.',
          },
          {
            destinationName: 'Hồ Hoàn Kiếm',
            sequenceOrder: 3,
            startTime: '19:00',
            endTime: '21:30',
            estimatedCost: 50_000,
            travelDistanceKm: 0.5,
            travelDurationMinutes: 8,
            travelMode: 'WALKING',
            note: 'Thưởng ngoạn không gian đi bộ lung linh ánh đèn cuối tuần.',
          },
        ],
      },
      {
        dayNumber: 3,
        note: 'Sáng sớm tĩnh lặng ven hồ và mua sắm quà lưu niệm phố phường',
        itineraries: [
          {
            destinationName: 'Hồ Hoàn Kiếm',
            sequenceOrder: 1,
            startTime: '06:30',
            endTime: '08:30',
            estimatedCost: 0,
            travelDistanceKm: 0.5,
            travelDurationMinutes: 10,
            travelMode: 'WALKING',
            note: 'Đón bình minh trong trẻo và ngắm tháp Rùa ẩn hiện trong sương sớm.',
          },
          {
            destinationName: 'Phố cổ Hà Nội',
            sequenceOrder: 2,
            startTime: '09:30',
            endTime: '12:00',
            estimatedCost: 200_000,
            travelDistanceKm: 1.0,
            travelDurationMinutes: 12,
            travelMode: 'WALKING',
            note: 'Mua ô mai Hàng Đường, bánh cốm Hàng Than làm quà lưu niệm.',
          },
        ],
      },
    ],
  },

  // ─── TRIP 2: Hành trình Ninh Bình ────────────────────────────────────────────
  {
    userEmail: 'demo.ha@example.com',
    name: 'Hành trình non nước Tràng An – Ninh Bình',
    destinationCity: 'Ninh Bình',
    startDate: '2026-10-15',
    endDate: '2026-10-16',
    budget: 2_800_000,
    numberOfPeople: 2,
    description: 'Khám phá non nước hữu tình cố đô Hoa Lư, ngồi thuyền len lỏi qua các hang động Tràng An và Tam Cốc.',
    isPublic: true,
    isAiGenerated: false,
    shareToken: 'demo-share-trip-ninhbinh-02',
    days: [
      {
        dayNumber: 1,
        note: 'Du ngoạn quần thể Tràng An và xuôi dòng sông Ngô Đồng ngắm lúa chín',
        itineraries: [
          {
            destinationName: 'Quần thể danh thắng Tràng An',
            sequenceOrder: 1,
            startTime: '08:00',
            endTime: '12:00',
            estimatedCost: 500_000,
            travelDistanceKm: 10.0,
            travelDurationMinutes: 25,
            travelMode: 'DRIVING',
            note: 'Ngồi thuyền tham quan tuyến số 2 qua hang Lam, hang Vạng và đền Suối Tiên.',
          },
          {
            destinationName: 'Tam Cốc – Bích Động',
            sequenceOrder: 2,
            startTime: '14:30',
            endTime: '17:30',
            estimatedCost: 300_000,
            travelDistanceKm: 12.5,
            travelDurationMinutes: 20,
            travelMode: 'DRIVING',
            note: 'Xuôi thuyền trên dòng sông Ngô Đồng ngắm thung lũng đá vôi ngoạn mục.',
          },
        ],
      },
      {
        dayNumber: 2,
        note: 'Đạp xe khám phá đền chùa cổ kính và cảnh sắc làng quê bình dị',
        itineraries: [
          {
            destinationName: 'Tam Cốc – Bích Động',
            sequenceOrder: 1,
            startTime: '08:30',
            endTime: '11:30',
            estimatedCost: 100_000,
            travelDistanceKm: 4.0,
            travelDurationMinutes: 20,
            travelMode: 'CYCLING',
            note: 'Đạp xe qua con đường rợp bóng cây đến viếng chùa Bích Động thanh tịnh.',
          },
          {
            destinationName: 'Quần thể danh thắng Tràng An',
            sequenceOrder: 2,
            startTime: '14:00',
            endTime: '17:00',
            estimatedCost: 200_000,
            travelDistanceKm: 11.0,
            travelDurationMinutes: 22,
            travelMode: 'DRIVING',
            note: 'Thăm đền Trình và chụp ảnh kỷ niệm trước khi chia tay Ninh Bình.',
          },
        ],
      },
    ],
  },

  // ─── TRIP 3: Cuối tuần tại Hạ Long ──────────────────────────────────────────
  {
    userEmail: 'demo.binh@example.com',
    name: 'Cuối tuần du thuyền tại Vịnh Hạ Long',
    destinationCity: 'Quảng Ninh',
    startDate: '2026-10-22',
    endDate: '2026-10-24',
    budget: 7_500_000,
    numberOfPeople: 2,
    description: 'Trải nghiệm du thuyền ngắm hoàng hôn trên vịnh Hạ Long, chèo thuyền kayak và thưởng thức hải sản tươi ngon.',
    isPublic: true,
    isAiGenerated: false,
    shareToken: 'demo-share-trip-halong-03',
    days: [
      {
        dayNumber: 1,
        note: 'Lên du thuyền ngắm vịnh kỳ quan và ngắm hoàng hôn buông xuống',
        itineraries: [
          {
            destinationName: 'Vịnh Hạ Long',
            sequenceOrder: 1,
            startTime: '12:00',
            endTime: '16:30',
            estimatedCost: 1_500_000,
            travelDistanceKm: 5.0,
            travelDurationMinutes: 30,
            travelMode: 'TRANSIT',
            note: 'Check-in du thuyền 5 sao, ăn trưa ngắm hòn Chó Đá, hòn Đỉnh Hương.',
          },
          {
            destinationName: 'Vịnh Hạ Long',
            sequenceOrder: 2,
            startTime: '17:00',
            endTime: '19:30',
            estimatedCost: 0,
            travelDistanceKm: 0.5,
            travelDurationMinutes: 10,
            travelMode: 'WALKING',
            note: 'Thưởng thức tiệc trà hoàng hôn trên boong tàu và nghe giới thiệu hải trình.',
          },
        ],
      },
      {
        dayNumber: 2,
        note: 'Khám phá hang động kỳ vĩ và chèo kayak hòa mình vào làn nước ngọc bích',
        itineraries: [
          {
            destinationName: 'Vịnh Hạ Long',
            sequenceOrder: 1,
            startTime: '08:00',
            endTime: '11:30',
            estimatedCost: 400_000,
            travelDistanceKm: 8.0,
            travelDurationMinutes: 40,
            travelMode: 'DRIVING',
            note: 'Leo bậc đá khám phá thạch nhũ lung linh trong hang Sửng Sốt.',
          },
          {
            destinationName: 'Vịnh Hạ Long',
            sequenceOrder: 2,
            startTime: '14:30',
            endTime: '17:00',
            estimatedCost: 150_000,
            travelDistanceKm: 2.0,
            travelDurationMinutes: 20,
            travelMode: 'WALKING',
            note: 'Tự tay chèo kayak luồn qua vòm hang Luồn ngắm vách đá vôi sừng sững.',
          },
        ],
      },
      {
        dayNumber: 3,
        note: 'Đón bình minh trong lành trên mặt vịnh và kết thúc chuyến đi',
        itineraries: [
          {
            destinationName: 'Vịnh Hạ Long',
            sequenceOrder: 1,
            startTime: '07:30',
            endTime: '10:30',
            estimatedCost: 200_000,
            travelDistanceKm: 6.0,
            travelDurationMinutes: 35,
            travelMode: 'TRANSIT',
            note: 'Tập bài Thái Cực Quyền đón tia nắng sớm và thưởng thức bữa sáng nhẹ nhàng.',
          },
        ],
      },
    ],
  },

  // ─── TRIP 4: Di sản miền Trung ──────────────────────────────────────────────
  {
    userEmail: 'demo.khanh@example.com',
    name: 'Hành trình Di sản miền Trung: Đà Nẵng – Hội An – Huế',
    destinationCity: 'Đà Nẵng',
    startDate: '2026-11-05',
    endDate: '2026-11-08',
    budget: 9_000_000,
    numberOfPeople: 2,
    description: 'Hành trình kết nối các di sản văn hóa thế giới: Phố cổ Hội An, Thánh địa Mỹ Sơn, Bà Nà Hills và Cố đô Huế.',
    isPublic: true,
    isAiGenerated: false,
    shareToken: 'demo-share-trip-mientrung-04',
    days: [
      {
        dayNumber: 1,
        note: 'Tận hưởng bờ biển Mỹ Khê và ngắm toàn cảnh vịnh Đà Nẵng từ Sơn Trà',
        itineraries: [
          {
            destinationName: 'Bãi biển Mỹ Khê',
            sequenceOrder: 1,
            startTime: '07:30',
            endTime: '10:30',
            estimatedCost: 50_000,
            travelDistanceKm: 1.5,
            travelDurationMinutes: 15,
            travelMode: 'WALKING',
            note: 'Dạo bộ tắm biển buổi sớm trên bãi cát mịn màng ngắm bình minh.',
          },
          {
            destinationName: 'Bán đảo Sơn Trà',
            sequenceOrder: 2,
            startTime: '14:00',
            endTime: '17:30',
            estimatedCost: 150_000,
            travelDistanceKm: 12.0,
            travelDurationMinutes: 25,
            travelMode: 'DRIVING',
            note: 'Viếng chùa Linh Ứng ngắm tượng Phật Quan Thế Âm cao 67m hướng ra biển lớn.',
          },
        ],
      },
      {
        dayNumber: 2,
        note: 'Chinh phục Cầu Vàng trên mây và lạc bước vào phố cổ Hội An rực rỡ',
        itineraries: [
          {
            destinationName: 'Bà Nà Hills',
            sequenceOrder: 1,
            startTime: '08:30',
            endTime: '15:30',
            estimatedCost: 1_800_000,
            travelDistanceKm: 35.0,
            travelDurationMinutes: 50,
            travelMode: 'DRIVING',
            note: 'Đi cáp treo ngắm rừng nguyên sinh, check-in Cầu Vàng trứ danh và Làng Pháp.',
          },
          {
            destinationName: 'Phố cổ Hội An',
            sequenceOrder: 2,
            startTime: '17:30',
            endTime: '21:30',
            estimatedCost: 250_000,
            travelDistanceKm: 45.0,
            travelDurationMinutes: 55,
            travelMode: 'DRIVING',
            note: 'Ngắm phố cổ lung linh đèn lồng, thả hoa đăng nguyện ước trên dòng sông Hoài.',
          },
        ],
      },
      {
        dayNumber: 3,
        note: 'Chiêm bái tháp Chăm cổ kính Mỹ Sơn và khám phá ẩm thực Hội An',
        itineraries: [
          {
            destinationName: 'Thánh địa Mỹ Sơn',
            sequenceOrder: 1,
            startTime: '08:00',
            endTime: '11:30',
            estimatedCost: 350_000,
            travelDistanceKm: 42.0,
            travelDurationMinutes: 60,
            travelMode: 'DRIVING',
            note: 'Thưởng thức điệu múa Apsara uyển chuyển và tìm hiểu nghệ thuật kiến trúc Chăm Pa.',
          },
          {
            destinationName: 'Phố cổ Hội An',
            sequenceOrder: 2,
            startTime: '15:00',
            endTime: '18:30',
            estimatedCost: 160_000,
            travelDistanceKm: 2.0,
            travelDurationMinutes: 15,
            travelMode: 'WALKING',
            note: 'Thưởng thức mì Quảng, bánh đập hến xào và nhâm nhi nước Mót thảo mộc.',
          },
        ],
      },
      {
        dayNumber: 4,
        note: 'Vượt đèo Hải Vân đến vùng đất cố đô Huế trầm mặc',
        itineraries: [
          {
            destinationName: 'Đại Nội Huế',
            sequenceOrder: 1,
            startTime: '09:00',
            endTime: '13:00',
            estimatedCost: 450_000,
            travelDistanceKm: 100.0,
            travelDurationMinutes: 120,
            travelMode: 'DRIVING',
            note: 'Qua đèo Hải Vân đến Huế, vào thăm Ngọ Môn, điện Thái Hòa và Tử Cấm Thành.',
          },
          {
            destinationName: 'Cố đô Huế',
            sequenceOrder: 2,
            startTime: '14:30',
            endTime: '17:30',
            estimatedCost: 200_000,
            travelDistanceKm: 8.0,
            travelDurationMinutes: 20,
            travelMode: 'TRANSIT',
            note: 'Dạo quanh các lăng tẩm trầm mặc và thưởng thức chè hẻm đậm đà xứ Huế.',
          },
        ],
      },
    ],
  },

  // ─── TRIP 5: Đà Lạt bình yên ───────────────────────────────────────────────
  {
    userEmail: 'demo.minh@example.com',
    name: 'Đà Lạt bình yên – Mùa sương phố núi',
    destinationCity: 'Lâm Đồng',
    startDate: '2026-11-12',
    endDate: '2026-11-14',
    budget: 4_500_000,
    numberOfPeople: 2,
    description: 'Tận hưởng khí hậu se lạnh mát lành của cao nguyên Lâm Viên, đạp xe ven hồ Xuân Hương và dạo đồi thông.',
    isPublic: true,
    isAiGenerated: false,
    shareToken: 'demo-share-trip-dalat-05',
    days: [
      {
        dayNumber: 1,
        note: 'Hòa mình vào không khí mát lành của thành phố sương mờ',
        itineraries: [
          {
            destinationName: 'Thành phố Đà Lạt',
            sequenceOrder: 1,
            startTime: '09:00',
            endTime: '12:00',
            estimatedCost: 100_000,
            travelDistanceKm: 5.0,
            travelDurationMinutes: 15,
            travelMode: 'TRANSIT',
            note: 'Nhận phòng nghỉ, ghé quán cà phê dốc ngắm cảnh thung lũng thông reo.',
          },
          {
            destinationName: 'Hồ Xuân Hương',
            sequenceOrder: 2,
            startTime: '15:00',
            endTime: '18:00',
            estimatedCost: 50_000,
            travelDistanceKm: 2.0,
            travelDurationMinutes: 20,
            travelMode: 'WALKING',
            note: 'Dạo bước ven hồ thơ mộng, thưởng thức bánh tráng nướng và sữa chua phô mai.',
          },
        ],
      },
      {
        dayNumber: 2,
        note: 'Khám phá kiến trúc Đông Dương hoài cổ và nhịp sống chợ đêm phố núi',
        itineraries: [
          {
            destinationName: 'Thành phố Đà Lạt',
            sequenceOrder: 1,
            startTime: '08:30',
            endTime: '11:30',
            estimatedCost: 200_000,
            travelDistanceKm: 8.0,
            travelDurationMinutes: 20,
            travelMode: 'DRIVING',
            note: 'Tham quan ga xe lửa Đà Lạt cổ kính với đầu tàu hơi nước độc đáo.',
          },
          {
            destinationName: 'Hồ Xuân Hương',
            sequenceOrder: 2,
            startTime: '18:00',
            endTime: '21:00',
            estimatedCost: 120_000,
            travelDistanceKm: 1.5,
            travelDurationMinutes: 15,
            travelMode: 'WALKING',
            note: 'Uống sữa đậu nành nóng hổi và dạo chợ đêm Đà Lạt mua áo len ấm áp.',
          },
        ],
      },
      {
        dayNumber: 3,
        note: 'Săn sương sớm quanh hồ và chọn mua đặc sản cao nguyên làm quà',
        itineraries: [
          {
            destinationName: 'Hồ Xuân Hương',
            sequenceOrder: 1,
            startTime: '06:00',
            endTime: '08:30',
            estimatedCost: 60_000,
            travelDistanceKm: 5.0,
            travelDurationMinutes: 30,
            travelMode: 'CYCLING',
            note: 'Đạp xe đạp đôi săn sương sớm giăng kín mặt nước hồ tĩnh lặng.',
          },
          {
            destinationName: 'Thành phố Đà Lạt',
            sequenceOrder: 2,
            startTime: '10:00',
            endTime: '12:30',
            estimatedCost: 350_000,
            travelDistanceKm: 4.0,
            travelDurationMinutes: 15,
            travelMode: 'DRIVING',
            note: 'Mua mứt dâu tây, trà atiso và hồng treo gió trứ danh của Đà Lạt.',
          },
        ],
      },
    ],
  },

  // ─── TRIP 6: Nghỉ dưỡng Phú Quốc ──────────────────────────────────────────
  {
    userEmail: 'demo.linh@example.com',
    name: 'Thiên đường nghỉ dưỡng biển Đảo Ngọc Phú Quốc',
    destinationCity: 'Kiên Giang',
    startDate: '2026-11-20',
    endDate: '2026-11-23',
    budget: 12_000_000,
    numberOfPeople: 2,
    description: 'Tận hưởng biển xanh nắng vàng Phú Quốc, lặn ngắm san hô rực rỡ và thưởng thức hải sản tươi ngon.',
    isPublic: true,
    isAiGenerated: false,
    shareToken: 'demo-share-trip-phuquoc-06',
    days: [
      {
        dayNumber: 1,
        note: 'Đến đảo ngọc, nhận resort và ngắm hoàng hôn rực rỡ trên biển Tây',
        itineraries: [
          {
            destinationName: 'Đảo Phú Quốc',
            sequenceOrder: 1,
            startTime: '14:00',
            endTime: '18:00',
            estimatedCost: 300_000,
            travelDistanceKm: 15.0,
            travelDurationMinutes: 25,
            travelMode: 'TRANSIT',
            note: 'Check-in resort view biển Bãi Trường, tắm biển thư giãn ngắm hoàng hôn.',
          },
        ],
      },
      {
        dayNumber: 2,
        note: 'Tour cano khám phá các hòn đảo hoang sơ và ẩm thực chợ đêm',
        itineraries: [
          {
            destinationName: 'Đảo Phú Quốc',
            sequenceOrder: 1,
            startTime: '08:30',
            endTime: '13:30',
            estimatedCost: 1_200_000,
            travelDistanceKm: 25.0,
            travelDurationMinutes: 40,
            travelMode: 'DRIVING',
            note: 'Tour cano 4 đảo, lặn ngắm rạn san hô tự nhiên tại hòn Mây Rút và hòn Móng Tay.',
          },
          {
            destinationName: 'Đảo Phú Quốc',
            sequenceOrder: 2,
            startTime: '17:30',
            endTime: '21:00',
            estimatedCost: 500_000,
            travelDistanceKm: 18.0,
            travelDurationMinutes: 30,
            travelMode: 'DRIVING',
            note: 'Dạo chợ đêm Dương Đông, thưởng thức bún quậy Kiến Xây và hải sản nướng mỡ hành.',
          },
        ],
      },
      {
        dayNumber: 3,
        note: 'Trải nghiệm cáp treo vượt biển và nghệ thuật hoàng hôn bên bờ cát',
        itineraries: [
          {
            destinationName: 'Đảo Phú Quốc',
            sequenceOrder: 1,
            startTime: '09:00',
            endTime: '14:00',
            estimatedCost: 1_200_000,
            travelDistanceKm: 30.0,
            travelDurationMinutes: 45,
            travelMode: 'DRIVING',
            note: 'Trải nghiệm cáp treo Hòn Thơm vượt biển ngắm toàn cảnh làng chài An Thới.',
          },
          {
            destinationName: 'Đảo Phú Quốc',
            sequenceOrder: 2,
            startTime: '16:00',
            endTime: '19:00',
            estimatedCost: 200_000,
            travelDistanceKm: 2.0,
            travelDurationMinutes: 15,
            travelMode: 'WALKING',
            note: 'Thư giãn check-in bên bờ biển với các tác phẩm nghệ thuật voi chân dài độc đáo.',
          },
        ],
      },
      {
        dayNumber: 4,
        note: 'Tham quan các làng nghề truyền thống và mua quà đặc sản',
        itineraries: [
          {
            destinationName: 'Đảo Phú Quốc',
            sequenceOrder: 1,
            startTime: '08:30',
            endTime: '11:30',
            estimatedCost: 250_000,
            travelDistanceKm: 10.0,
            travelDurationMinutes: 20,
            travelMode: 'DRIVING',
            note: 'Thăm cơ sở ngọc trai Phú Quốc và vườn hồ tiêu truyền thống mua quà.',
          },
        ],
      },
    ],
  },

  // ─── TRIP 7: Sài Gòn và Củ Chi ──────────────────────────────────────────────
  {
    userEmail: 'demo.chi@example.com',
    name: 'Khám phá Sài Gòn sôi động và Địa đạo Củ Chi hào hùng',
    destinationCity: 'TP. Hồ Chí Minh',
    startDate: '2026-12-04',
    endDate: '2026-12-06',
    budget: 5_000_000,
    numberOfPeople: 2,
    description: 'Hành trình kết hợp giữa nhịp sống đô thị hiện đại của TP.HCM và dấu ấn lịch sử hào hùng tại Củ Chi.',
    isPublic: true,
    isAiGenerated: false,
    shareToken: 'demo-share-trip-saigon-07',
    days: [
      {
        dayNumber: 1,
        note: 'Khám phá các biểu tượng lịch sử và kiến trúc giữa trung tâm quận 1',
        itineraries: [
          {
            destinationName: 'Chợ Bến Thành',
            sequenceOrder: 1,
            startTime: '09:00',
            endTime: '12:00',
            estimatedCost: 150_000,
            travelDistanceKm: 1.0,
            travelDurationMinutes: 10,
            travelMode: 'WALKING',
            note: 'Khám phá khu chợ biểu tượng hơn một thế kỷ, nếm thử bánh bèo và chè Sài Gòn.',
          },
          {
            destinationName: 'Dinh Độc Lập',
            sequenceOrder: 2,
            startTime: '14:00',
            endTime: '17:00',
            estimatedCost: 120_000,
            travelDistanceKm: 1.2,
            travelDurationMinutes: 15,
            travelMode: 'WALKING',
            note: 'Tham quan di tích lịch sử đặc biệt quốc gia, ngắm kiến trúc hiện đại của KTS Ngô Viết Thụ.',
          },
        ],
      },
      {
        dayNumber: 2,
        note: 'Chuyến đi về nguồn thăm vùng đất thép thành đồng Củ Chi',
        itineraries: [
          {
            destinationName: 'Địa đạo Củ Chi',
            sequenceOrder: 1,
            startTime: '08:00',
            endTime: '14:00',
            estimatedCost: 500_000,
            travelDistanceKm: 55.0,
            travelDurationMinutes: 80,
            travelMode: 'DRIVING',
            note: 'Trải nghiệm chui hệ thống đường hầm bí mật dưới lòng đất và thưởng thức khoai mì chấm muối mè.',
          },
          {
            destinationName: 'Chợ Bến Thành',
            sequenceOrder: 2,
            startTime: '17:30',
            endTime: '20:30',
            estimatedCost: 100_000,
            travelDistanceKm: 50.0,
            travelDurationMinutes: 75,
            travelMode: 'DRIVING',
            note: 'Thưởng thức ẩm thực đêm náo nhiệt quanh khu vực chợ với các món nướng hấp dẫn.',
          },
        ],
      },
      {
        dayNumber: 3,
        note: 'Thư thái cà phê sáng công viên và mua sắm bánh trái Nam Bộ',
        itineraries: [
          {
            destinationName: 'Dinh Độc Lập',
            sequenceOrder: 1,
            startTime: '08:30',
            endTime: '11:00',
            estimatedCost: 80_000,
            travelDistanceKm: 0.8,
            travelDurationMinutes: 10,
            travelMode: 'WALKING',
            note: 'Dạo quanh công viên Tao Đàn rợp bóng cây cổ thụ và nhâm nhi cà phê sữa đá.',
          },
          {
            destinationName: 'Chợ Bến Thành',
            sequenceOrder: 2,
            startTime: '13:00',
            endTime: '16:00',
            estimatedCost: 300_000,
            travelDistanceKm: 1.0,
            travelDurationMinutes: 12,
            travelMode: 'WALKING',
            note: 'Mua bánh pía Sóc Trăng, kẹo dừa Bến Tre và cà phê Robusta làm quà biếu.',
          },
        ],
      },
    ],
  },
];
